### PR TITLE
Add serde feature to Scrolling, CursorMove and Input enums

### PR DESCRIPTION
**Pull request by cestef**
Some projects may need a serde feature to have serializable Scrolling, CursorMove and Input enums

### CODE REVIEW

**Comment by cestef** [comment]
using a configuration to remap keys, and thus the need for serialization and deserialization of some structs

**Comment by joshka** [comment]
> I'm trying to minimize dependencies as minimal as possible. What is your use case of this feature in real world?

Generally making the dependency optional and feature flag gating each place it's used like this is fine. Most people would expect this.

One downside of introducing serialization to structs is that it means that breaking changes break serialization, but the benefits outweigh this problem generally.

**Comment by rhysd** [comment]
> using a configuration to remap keys, and thus the need for serialization and deserialization of some structs

Okay, that usage makes sense.

> Generally making the dependency optional and feature flag gating each place it's used like this is fine. Most people would expect this.

I agree. But even if it is an optional dependency, it increases the maintenance cost. I wanted to know the feature really cost the increase. In addition, this change introduces `Eq` boundary to the types. It is okay for now, but it means `Eq` needs to be implemented for their all fields. For example, float number values can no longer be a field of those types without breaking change.

**Review by rhysd — CHANGES_REQUESTED** [review]
I will revisit this PR for reviewing code within this week.

Can you apply the following patch and ensure no error happens with `cargo clippy --features serde`?

```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 6396f1c..4cd17e5 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,6 +45,7 @@ jobs:
       - run: cargo fmt -- --check
       - run: cargo clippy --examples --tests -- -D warnings
       - run: cargo clippy --examples --tests --features search -- -D warnings
+      - run: cargo clippy --examples --tests --features serde -- -D warnings
       - run: cargo clippy --examples --tests --no-default-features --features termion -- -D warnings
       - run: cargo clippy --examples --tests --no-default-features --features termion,search -- -D warnings
       - run: cargo clippy --examples --tests --no-default-features --features termwiz -- -D warnings
```

**Comment by cestef** [comment]
Should be good, sorry for the force push, accidentally reformatted the whole ci file :/

**Review by rhysd — APPROVED** [review]

**Comment by rhysd** [comment]
I'll release this feature after adding more tests and docs. Thank you for making this PR.

**Comment by rhysd** [comment]
[v0.5.1](https://github.com/rhysd/tui-textarea/releases/tag/v0.5.1) was released.

**Pull request merged**
