### PR TITLE
Alignment for TextArea

### PR DESCRIPTION
**Pull request by Volkalex28**

### CODE REVIEW

**Comment by rhysd** [comment]
Can you describe the motivation? Setting center or right alignment to text editor sounds strange for me.

**Comment by Volkalex28** [comment]
Good day.  

Alignment seemed like a good idea to me when this library is used in single line mode.  If I want to embed a field somewhere to change the row, I might need to align it to the center or to the right. For example, I needed it to change table cells.  Some of the data is strings and numbers. Your library is best suited for this role, but since the cells are aligned in the center according to the style of the table, it is necessary to align in your widget too. 

If you want I can test line number alignment when I get a chance and/or fix this functionality

**Comment by Volkalex28** [comment]
> Can you describe the motivation? Setting center or right alignment to text editor sounds strange for me.
> 
> I don't think that alignments other than left work with line numbers well.

Good day.  

Alignment seemed like a good idea to me when this library is used in single line mode.  If I want to embed a field somewhere to change the row, I might need to align it to the center or to the right. For example, I needed it to change table cells.  Some of the data is strings and numbers. Your library is best suited for this role, but since the cells are aligned in the center according to the style of the table, it is necessary to align in your widget too. 

If you want I can test line number alignment when I get a chance and/or fix this functionality

**Comment by rhysd** [comment]
Thanks for the explanation. I understood you use case and it sounds reasonable. Let me try this branch on my side before merging.

> If you want I can test line number alignment when I get a chance and/or fix this functionality

Your use case doesn't seem to need line numbers, so I think simply disabling line numbers would be sufficient. After merging this branch, I'll add the implementation.

**Comment by rhysd** [comment]
@Volkalex28 Can you fix formatter issue?

```
cargo fmt
```

**Comment by Volkalex28** [comment]
> @Volkalex28 Can you fix formatter issue?
> 
> ```
> cargo fmt
> ```

Yes. I will check

**Review by rhysd — APPROVED** [review]
OK, now I have time. I'll fix linter warnings after merging this.

**Comment by rhysd** [comment]
v0.1.6 was released.

**Pull request merged**
